# Generated by Django 6.1.1 on 2026-09-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pin',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
