# Generated by Django 6.1.1 on 2026-10-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_student_parent'),
        ('portal', '0003_student_parent_nullable'),
    ]

    operations = [
    ]
