# Generated by Django 6.1.1 on 2026-10-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_merge_20261004_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
