# Generated by Django 6.1.1 on 2026-10-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_student_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pin',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
